baseURL = "https://halcyon.hr"
languageCode = "en-us"
title = "the halcyon blog"
theme = "halcyon2"

[params]
description = "Occasional blog posts about programming, tech, and other general issues of interest to a common nerd."
author = "Ivan Oštrić"
