baseURL = "https://www.halcyon.hr"
languageCode = "en-us"
title = "the halcyon blog"
theme = "halcyon2"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
pygmentsOptions="linenos=false"

[params]
description = "Occasional blog posts about programming, tech, and other general issues of interest to a common nerd."
author = "Ivan Oštrić"

[social]
twitter = "somwhatparanoid"
